export const site = {
  name: 'Fotógrafos para Bodas',
  domain: 'fotografosparabodas.es',
  tagline: 'Encuentra tu Fotógrafo de Bodas Ideal',
  description: 'Directorio de los mejores fotógrafos de bodas en España. Compara estilos y disponibilidad. Fotógrafos verificados con premios internacionales en Madrid, Málaga, Bilbao y más ciudades.',
  phone: '625677487',
  whatsapp: '34625677487',
  email: 'hola@fotografosparabodas.es',
};

export const cities = [
  { slug: 'madrid',        name: 'Madrid',        province: 'Madrid',    region: 'Comunidad de Madrid' },
  { slug: 'malaga',        name: 'Málaga',        province: 'Málaga',    region: 'Andalucía' },
  { slug: 'zaragoza',      name: 'Zaragoza',      province: 'Zaragoza',  region: 'Aragón' },
  { slug: 'murcia',        name: 'Murcia',        province: 'Murcia',    region: 'Murcia' },
  { slug: 'bilbao',        name: 'Bilbao',        province: 'Bizkaia',   region: 'País Vasco' },
  { slug: 'cordoba',       name: 'Córdoba',       province: 'Córdoba',   region: 'Andalucía' },
  { slug: 'alicante',      name: 'Alicante',      province: 'Alicante',  region: 'Valencia' },
  { slug: 'valladolid',    name: 'Valladolid',    province: 'Valladolid',region: 'Castilla' },
  { slug: 'granada',       name: 'Granada',       province: 'Granada',   region: 'Andalucía' },
  { slug: 'san-sebastian', name: 'San Sebastián', province: 'Gipuzkoa', region: 'País Vasco' },
  { slug: 'sevilla',       name: 'Sevilla',       province: 'Sevilla',   region: 'Andalucía' },
  { slug: 'valencia',      name: 'Valencia',      province: 'Valencia',  region: 'Valencia' },
  { slug: 'barcelona',     name: 'Barcelona',     province: 'Barcelona', region: 'Cataluña' },
  { slug: 'toledo',        name: 'Toledo',        province: 'Toledo',    region: 'Castilla-La Mancha' },
  { slug: 'pamplona',      name: 'Pamplona',      province: 'Navarra',   region: 'Navarra' },
  { slug: 'logrono',       name: 'Logroño',       province: 'La Rioja',  region: 'La Rioja' },
  { slug: 'santander',     name: 'Santander',     province: 'Cantabria', region: 'Cantabria' },
  { slug: 'galicia',       name: 'Galicia',       province: 'A Coruña',  region: 'Galicia' },
  { slug: 'oviedo',        name: 'Oviedo',        province: 'Asturias',  region: 'Asturias' },
  { slug: 'mallorca',      name: 'Mallorca',      province: 'Baleares',  region: 'Islas Baleares' },
  { slug: 'tenerife',      name: 'Tenerife',      province: 'Santa Cruz de Tenerife', region: 'Canarias' },
  { slug: 'caceres',       name: 'Cáceres',       province: 'Cáceres',   region: 'Extremadura' },
];
